name: Backend Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    env: 
      TESTING: sqlite:///:memory
      SECRET_KEY: 123456
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

